### ISSUE TITLE
Lightning profile to reach end-of-life

### ISSUE THREAD

**Issue by phenaproxima** [NREL/opencommunications#1]
Hi there :) I'm the Lightning maintainer at Acquia, and I see that this appears to be a maintained sub-profile of Lightning. I thought I would drop in to inform you that Lightning is going to reach its end of life in November 2021 (see https://www.acquia.com/blog/acquia-lightning-eol-2021-acquia-cms-future), and therefore this package will probably need to drop its Lightning dependency and decouple the sub-profile by then. There is some documentation on how to do that available at https://github.com/acquia/lightning/wiki/Uninstalling-Lightning#decoupling-a-sub-profile-from-lightning. Please let me know if I can be of any assistance!

**Comment by ShaunLawsNREL** [comment]
Hi Adam. Thanks, yes, we are aware that Lightning EOL is November 2021 . The Drupal 8 version of this profile will reach end-of-life at the same time. We are currently working to create a simplified Drupal 9 profile for our own purposes, which will not implement the same out-of-the-box functionality currently in the profile, and that does not have the dependency on Lightning.
